name: CI Pipeline

on:
  push:
    branches:
      - main # This workflow will run on pushes to the 'main' branch
  pull_request:
    branches:
      - main # This workflow will run on pull requests targeting the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install dependencies from requirements.txt
        pip install pytest # Ensure pytest is installed

    - name: Run tests
      run: |
        # Explicitly run pytest from the root of the repository to ensure 'app' is in path
        python -m pytest test/
      env:
        PYTHONPATH: . # The dot '.' means the current working directory (which is the root of the repo)

    - name: Build Docker image
      run: |
        docker build -t expense-tracker-app:latest . # Build the Docker image